4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
t1 = np.empty((2,2))
print(t1)

[[1.5e-323 2.0e-323]
 [3.0e-323 3.5e-323]]


2. Initialize an all one array with size 4X2.

In [ ]:
t2 = np.ones((4,2))
print(t2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
t3 = np.full((3, 3), 7)
print(t3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
e1 = np.array([[8,4], [2, 5]])
t4 = np.zeros_like(e1)
print(t4)

[[0 0]
 [0 0]]


In [ ]:
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
e2 = np.array([[3, 4],[6, 7], [5, 3]])
t5 = np.ones_like(e2)
print(t5)

[[1 1]
 [1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
t6 = np.array(new_list)
print(t6)

[1 2 3 4]


##Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
a1 = np.arange(10, 50)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
a2 = np.arange(9).reshape(3,3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
a3 = np.eye(3)
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a4 = np.random.random(30)
print("Mean:", a4.mean())

Mean: 0.4837112683648687


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
a5 = np.random.random((10,10))
print("Minimum:", a5.min())
print("Maximum:", a5.max())

Minimum: 0.011427458899327392
Maximum: 0.9608208690914614


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
a6 = np.zeros(10)
a6[4] = 1
print(a6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = [1,2,0,0,4,0]
print(arr[::-1])

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
a7 = np.ones((5,5))
a7[1:-1,1:-1] = 0
print(a7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
a8 = np.zeros((8,8),dtype=int)
a8[1::2, ::2] = 1
a8[::2, 1::2] = 1
print(a8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.

In [ ]:
print(x+y)

[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
print(x-y)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
print(x * 7)

[[ 7 14]
 [21 35]]


4. Find the square of each element of the array.

In [ ]:
print(x**2)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
print("v dot w:", np.dot(v, w))
print("x dot v:", np.dot(x, v))
print("x dot y:", np.dot(x, y))

v dot w: 219
x dot v: [29 77]
x dot y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
print(np.concatenate((x,y), axis=0))
print(np.column_stack((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


This gives error because shapes are not matching (2x2 and 1x2)

# Problem - 4: Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

In [ ]:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

1. Prove A.A−1 = I.

In [ ]:
print(np.dot(A, np.linalg.inv(A)))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


## 2. Prove AB ≠ BA

In [ ]:
print(np.dot(A,B))
print(np.dot(B,A))
print("Clearly we can see they are not equal")

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Clearly we can see they are not equal


3. Prove (AB)^T = B^T A^T

In [ ]:
print((np.dot(A,B)).T)
print(np.dot(B.T, A.T))

print("Clearly we can see they are equal")

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
Clearly we can see they are equal


# • Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
A1 = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B2 = np.array([-1,-3,9])

X = np.linalg.solve(A1,B2)
print(X)

[ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
A1_inv = np.linalg.inv(A1)
solution2 = np.dot(A1_inv, B2)
print("\nSolution using A^-1 * B:\n", solution2)


Solution using A^-1 * B:
 [ 2.  1. -2.]


# 4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

In [ ]:
import time
import numpy as np

# For Lists in Pythons

l1 = list(range(1_000_000))
l2 = list(range(1_000_000))

start_time = time.time()
listadd=[l1[i] + l2[i] for i in range(len(l1))]
end = time.time()

print("Python List Time taken:", end-start_time)

# For NumPy Arrays
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start_time = time.time()
arr3 = arr1 + arr2
end = time.time()

print("NumPy Time taken:", end-start_time)


Python List Time taken: 0.11282610893249512
NumPy Time taken: 0.003834247589111328


# 2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
# For Python Lists
start = time.time()
list_mul = [l1[i]*l2[i] for i in range (1_000_000)]
end = time.time()

print("Python List Time taken:", end-start)

# For NumPy Arrays
start = time.time()
np_mul = np.multiply(arr1, arr2)
end = time.time()

print("NumPy Time taken:", end-start)

Python List Time taken: 0.1206972599029541
NumPy Time taken: 0.0049397945404052734


# 3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
# For Python List
start = time.time()
dot_list = sum(l1[i]*l2[i] for i in range(1_000_000))
end = time.time()

print("Python List Time taken:", end-start)

# For NumPy Arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()

print("NumPy Time taken:", end-start)

Python List Time taken: 0.12076282501220703
NumPy Time taken: 0.002113819122314453


# 4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [10]:
#Python List (Nested List)
m1 = [[1]* 1000 for _ in range(1000)]
m2 = [[1]* 1000 for _ in range(1000)]
start = time.time()

#Manual Matrix Multiplication
result = [[sum(m1[i][k]*m2[i][k] for k in range(1000)) for j in range(1000)] for i in range (1000)]
end = time.time()
print("Python List Time taken:", end-start)

#NumPy Arrays
P = np.ones((1000,1000))
Q = np.ones((1000,1000))
start = time.time()
R = np.dot(P,Q)
end = time.time()
print("NumPy Matrix Multiplicatoin Time: ",end-start)

Python List Time taken: 103.11893844604492
NumPy Matrix Multiplicatoin Time:  0.06523919105529785
